FROM node:18
ARG AZURE_AD_CLIENT_SECRET
ARG DATABASE_URL
ARG SHADOW_DATABASE_URL
ARG NEXT_PUBLIC_AZURE_AD_APPLICATION_ID
ARG NEXT_PUBLIC_AZURE_AD_DIRECTORY_ID
ENV AZURE_AD_CLIENT_SECRET ${AZURE_AD_CLIENT_SECRET}
ENV DATABASE_URL ${DATABASE_URL}
ENV SHADOW_DATABASE_URL ${SHADOW_DATABASE_URL}
ENV NEXT_PUBLIC_AZURE_AD_APPLICATION_ID ${NEXT_PUBLIC_AZURE_AD_APPLICATION_ID}
ENV NEXT_PUBLIC_AZURE_AD_DIRECTORY_ID ${NEXT_PUBLIC_AZURE_AD_DIRECTORY_ID}

WORKDIR /usr/app

RUN npm ci

RUN npm run build

CMD [ "npm", "start" ]